
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api_gateway
  namespace: orpaynter
  labels:
    app: api_gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api_gateway
  template:
    metadata:
      labels:
        app: api_gateway
    spec:
      containers:
      - name: api_gateway
        image: orpaynter/api-gateway:latest
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: api_gateway-service
  namespace: orpaynter
spec:
  selector:
    app: api_gateway
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
---
