
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile_api
  namespace: orpaynter
  labels:
    app: mobile_api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobile_api
  template:
    metadata:
      labels:
        app: mobile_api
    spec:
      containers:
      - name: mobile_api
        image: orpaynter/mobile-api:latest
        ports:
        - containerPort: 8005
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8005
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8005
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: mobile_api-service
  namespace: orpaynter
spec:
  selector:
    app: mobile_api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8005
  type: ClusterIP
---
