
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project_service
  namespace: orpaynter
  labels:
    app: project_service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project_service
  template:
    metadata:
      labels:
        app: project_service
    spec:
      containers:
      - name: project_service
        image: orpaynter/project-service:latest
        ports:
        - containerPort: 8002
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: project_service-service
  namespace: orpaynter
spec:
  selector:
    app: project_service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8002
  type: ClusterIP
---
