
apiVersion: v1
kind: Secret
metadata:
  name: orpaynter-secrets
  namespace: orpaynter
type: Opaque
stringData:
  DB_PASSWORD: "your-db-password"
  REDIS_PASSWORD: "your-redis-password"
  STRIPE_SECRET_KEY: "your-stripe-secret"
  SENDGRID_API_KEY: "your-sendgrid-key"
---
