
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web_app
  namespace: orpaynter
  labels:
    app: web_app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web_app
  template:
    metadata:
      labels:
        app: web_app
    spec:
      containers:
      - name: web_app
        image: orpaynter/web-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: web_app-service
  namespace: orpaynter
spec:
  selector:
    app: web_app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
---
