version: '3.8'

services:
  postgresql:
    image: postgres:14
    environment:
      POSTGRES_DB: orpaynter
      POSTGRES_USER: orpaynter
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: orpaynter
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  api-gateway:
    build: ./services/api-gateway
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://orpaynter:password@postgresql:5432/orpaynter
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgresql
      - redis

  user-service:
    build: ./services/user-service
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: postgresql://orpaynter:password@postgresql:5432/orpaynter
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgresql
      - redis

  project-service:
    build: ./services/project-service
    ports:
      - "8002:8002"
    environment:
      DATABASE_URL: postgresql://orpaynter:password@postgresql:5432/orpaynter
      MONGO_URL: mongodb://orpaynter:password@mongodb:27017/orpaynter
    depends_on:
      - postgresql
      - mongodb

  ai-service:
    build: ./services/ai-service
    ports:
      - "8003:8003"
    environment:
      QDRANT_URL: http://qdrant:6333
      MONGO_URL: mongodb://orpaynter:password@mongodb:27017/orpaynter
    depends_on:
      - qdrant
      - mongodb

  payment-service:
    build: ./services/payment-service
    ports:
      - "8004:8004"
    environment:
      DATABASE_URL: postgresql://orpaynter:password@postgresql:5432/orpaynter
      STRIPE_SECRET_KEY: sk_test_...
    depends_on:
      - postgresql

  marketplace-service:
    build: ./services/marketplace-service
    ports:
      - "8005:8005"
    environment:
      DATABASE_URL: postgresql://orpaynter:password@postgresql:5432/orpaynter
      MONGO_URL: mongodb://orpaynter:password@mongodb:27017/orpaynter
    depends_on:
      - postgresql
      - mongodb

  web-app:
    build: ./frontend/web-app
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8000
    depends_on:
      - api-gateway

volumes:
  postgres_data:
  mongo_data:
  redis_data:
  qdrant_data:
