CREATE TABLE qualified_leads (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    conversation_id UUID,
    mcp_lead_id TEXT,
    contact_name TEXT NOT NULL,
    contact_email TEXT NOT NULL,
    contact_phone TEXT NOT NULL,
    property_address TEXT NOT NULL,
    city TEXT NOT NULL,
    state TEXT NOT NULL,
    zip_code TEXT NOT NULL,
    property_type TEXT NOT NULL,
    damage_type TEXT NOT NULL,
    damage_severity TEXT NOT NULL,
    damage_description TEXT,
    urgency_level INTEGER NOT NULL,
    has_insurance BOOLEAN DEFAULT FALSE,
    insurance_company TEXT,
    claim_filed BOOLEAN DEFAULT FALSE,
    is_decision_maker BOOLEAN DEFAULT FALSE,
    qualification_score INTEGER NOT NULL,
    priority_level TEXT NOT NULL,
    status TEXT DEFAULT 'new',
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);